package poker.players

import poker.*
import java.lang.Integer.max

class SirRaiseALot(override var name: String = "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +"sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas" +
    "sdafasfdasffffffffffffffffffffasdfasfasdfhasdfhasduifhasdyufgasdfhsdafhapioshfuidoasfhiasdhfuiashfuihasdiofhsdiofhsadfuihsdfihuhdas"
                   , var piet: Int = 1): AIPlayer {

    var maxBetThisRound = 0

    var myBetSoFar = 0

    var willingToBet = 0

    var minBet = 0

    var wealth = 0

    var hand = 0

    override fun move(state: Board, player: Player): PlayerAction {
        var cards = player.cards

        for (comminityCard in state.communityCards) {
            cards.add(comminityCard)
        }

        var renk = rankHand(cards)

        var highCard = renk.deciders[0]

        hand = renk.handRank

        maxBetThisRound = state.currentBet

        myBetSoFar = player.betThisRound

        minBet = state.minBet

        wealth = player.wealth

        if (state.communityCards.size == 0) {
            if (hand == 1) {
                setWillingToBetHighBeforeFlop()
                return raise(player)
            } else if (highCard >= 10) {
                setWillingToBetLowBeforeFlop()
                return raise(player)
            } else {
                return Check(player)
            }
        } else {
            if (hand > 1) {
                setWillingToBetHigh()
                return raise(player)
            } else if (hand == 1){
                setWillingToBetLow()
                return raise(player)
            } else {
                return Check(player)
            }
        }
    }

    fun raise(player: Player): PlayerAction {
        var henk = maxBetThisRound - myBetSoFar
        if ( henk < willingToBet) {
            return Raise(player, willingToBet)
        } else if (henk < willingToBet*1.5 || hand > 2) {
            return Call(player)
        }
        return Check(player)
    }

    fun setWillingToBetHigh() {
        willingToBet = max(minBet, wealth/(2*piet))
    }

    fun setWillingToBetLow() {
        willingToBet = max(minBet, wealth/(10*piet))
    }

    fun setWillingToBetHighBeforeFlop() {
        willingToBet = max(minBet, wealth/(10*piet))
    }

    fun setWillingToBetLowBeforeFlop() {
        willingToBet = max(minBet, wealth/(20*piet))
    }
}